# Generated by Django 6.0.1 on 2026-09-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('borrow_approved', 'Borrow Approved'), ('borrow_rejected', 'Borrow Rejected'), ('return_reminder', 'Return Reminder'), ('overdue', 'Overdue'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
