[pytest]
DJANGO_SETTINGS_MODULE = book_recommondation.settings
pythonpath = backend
python_files = tests.py test_*.py *_tests.py
addopts = 
    --strict-markers
    --disable-warnings
    -ra
testpaths = backend/accounts backend/books backend/borrows backend/analytics backend/messaging
norecursedirs = backend/bookenv frontend backend/staticfiles backend/media .git .github
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
