# Generated by Django 6.0.1 on 2026-01-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('returned', 'Returned'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
