# Generated by Django 6.0.1 on 2026-09-26 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookreview'),
        ('borrows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='borrow',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['requested', 'approved'])), fields=('user', 'book'), name='unique_active_or_requested_borrow'),
        ),
    ]
