[pytest]
DJANGO_SETTINGS_MODULE = book_recommondation.settings
python_files = tests.py test_*.py *_tests.py
addopts = 
    --strict-markers
    --disable-warnings
    -ra
testpaths = accounts books borrows analytics messaging
norecursedirs = bookenv staticfiles media .git .github
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
