# Generated by Django 6.0.1 on 2026-04-01 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('total_books', models.PositiveIntegerField(default=0)),
                ('in_stock_books', models.PositiveIntegerField(default=0)),
                ('out_of_stock_books', models.PositiveIntegerField(default=0)),
                ('students_count', models.PositiveIntegerField(default=0)),
                ('total_borrows', models.PositiveIntegerField(default=0)),
                ('requested_borrows', models.PositiveIntegerField(default=0)),
                ('approved_borrows', models.PositiveIntegerField(default=0)),
                ('returned_borrows', models.PositiveIntegerField(default=0)),
                ('active_students_total', models.PositiveIntegerField(default=0)),
                ('active_students_30d', models.PositiveIntegerField(default=0)),
                ('top_categories', models.JSONField(blank=True, default=list)),
                ('borrow_trends', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_snapshots', to='accounts.department')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('snapshot_date', 'department'), name='uniq_analytics_snapshot_date_department')],
            },
        ),
    ]
