# Generated by Django 6.0.1 on 2026-08-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('rate', 'Rate'), ('borrow', 'Borrow')], default='view', max_length=20),
        ),
    ]
