# Generated by Django 6.0.1 on 2026-09-19 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_approval_status'),
        ('books', '0002_alter_bookinteraction_interaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['department', 'quantity'], name='books_book_departm_e3e802_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-average_rating', '-ratings_count'], name='books_book_average_4deb7b_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinteraction',
            index=models.Index(fields=['book', 'interaction_type'], name='books_booki_book_id_3fc1cc_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinteraction',
            index=models.Index(fields=['user', 'interaction_type'], name='books_booki_user_id_02db7d_idx'),
        ),
    ]
