# Generated by Django 6.0.1 on 2026-04-01 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
        ('books', '0002_bookdwelltime_searchhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='book',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bookinteraction',
            name='sequence_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinteraction',
            name='session_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddIndex(
            model_name='bookinteraction',
            index=models.Index(fields=['user', 'session_id', 'sequence_order'], name='books_booki_user_id_d9f6ea_idx'),
        ),
    ]
