# Generated by Django 6.0.1 on 2026-04-01 10:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_department_book_embedding_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE books_book
                        ADD COLUMN embedding_tmp double precision[];

                        UPDATE books_book
                        SET embedding_tmp = CASE
                            WHEN embedding IS NULL THEN NULL
                            ELSE ARRAY(
                                SELECT jsonb_array_elements_text(embedding)::double precision
                            )
                        END;

                        ALTER TABLE books_book
                        DROP COLUMN embedding;

                        ALTER TABLE books_book
                        RENAME COLUMN embedding_tmp TO embedding;
                    """,
                    reverse_sql="""
                        ALTER TABLE books_book
                        ADD COLUMN embedding_tmp jsonb;

                        UPDATE books_book
                        SET embedding_tmp = to_jsonb(embedding);

                        ALTER TABLE books_book
                        DROP COLUMN embedding;

                        ALTER TABLE books_book
                        RENAME COLUMN embedding_tmp TO embedding;
                    """,
                )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='book',
                    name='embedding',
                    field=django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        blank=True,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
