# Generated by Django 6.0.1 on 2026-04-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_authors_alter_book_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.CharField(blank=True, db_index=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=900),
        ),
    ]
